### ISSUE TITLE
What to do when sending an email during the register procedure has failed?

### ISSUE THREAD

**Issue by jjggjg** [Code-Break0/SecureAuthSystem#10]
The register.php code controls whether the sendValidationEmail was successful.
When not, it returns a errorcode ($errors[] = $err + 9;):

If just the emailing fails, an account has been created in the database with this email address. If the user wants to try the procedure again afterwards, he will receive the error message that his email address already exists.

How should you solve this?

Best thanks.

**Comment by Code-Break0** [comment]
Very good point, there are a couple of solutions I can think of:

1. If you are able to reliably detect email failure you can delete the account upon failure
2. Don't allow account creation until the email is verified (use a separate table for all unverified users and add to users table once verified)
3. Probably the most commonly used that I can think of: create a screen to allow the user to resend emails so that if it fails or they lost the validation email they can try again
